#!/usr/bin/env sh

rsync -zav --exclude '*md' --force --update --delete-after ~/Documents/public_html/me $idark_ipmu:~/public_html/
rsync -zav --exclude '*md' --force --update --delete-after ~/Documents/public_html/Research $idark_ipmu:~/public_html/
rsync -zav --exclude '*md' --force --update --delete-after ~/Documents/public_html/tmp $idark_ipmu:~/public_html/
rsync -zav --exclude '*md' --force --update --delete-after ~/Documents/public_html/sys $idark_ipmu:~/public_html/
