#!/usr/bin/env sh
# Make sure we have rofi
command -v rofi >/dev/null 2>&1 || exit

# choose the server to login
chosen=$(grep -v "#" $HOME/.local/xshare/server.info | awk '{print $1}'| rofi -dmenu -i -p 'choose the ssh server' -lines 20)
[ "$chosen" != "" ] || exit

info=$(grep "$chosen" $HOME/.local/xshare/server.info)
s=$(echo "$info" | awk '{print $2}')

SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
foot --title "dialog" -e env SSH_AUTH_SOCK="$SOCK" scp "$s":~/.clipboard ~/.clipboard
wl-copy < ~/.clipboard

